export { default as MainPage } from './MainPage/MainPage';
export { default as AccountPage } from './AccountPage/AccountPage';
export { default as AddressPage } from './AddressPage/AddressPage';
export { default as CatalogPage } from './CatalogPage/CatalogPage';
export { default as CartPage } from './CartPage/CartPage';
export { default as LoginPage } from './LoginPage/LoginPage';
export { default as NotFoundPage } from './NotFoundPage/NotFoundPage';
export { default as ProductPage } from './ProductPage/ProductPage';
export { default as RegistrationPage } from './RegistrationPage/RegistrationPage';
